FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm ci --only=production

COPY server ./server

COPY server ./

EXPOSE 3005

CMD ["/usr/bin/env", "APP_PORT=3005", "node", "index.js"]