name: PR Build Check

on:
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read
  pull-requests: write

jobs:
  build-check:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run ESLint
      run: npx eslint src
      env:
        CI: true

    - name: Build React app
      run: npm run build
      env:
        CI: true
        # Treat warnings as errors to ensure clean builds
        GENERATE_SOURCEMAP: false

    - name: Check for build warnings
      shell: powershell
      run: |
        echo "✅ Build and lint checks completed successfully with no errors or warnings"
        echo "::notice::Pull request build and lint checks passed"

    - name: Build summary
      if: success()
      run: |
        echo "## ✅ Build Check Passed" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "The application builds successfully without errors or warnings." >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "- **Node.js version**: 18" >> $GITHUB_STEP_SUMMARY
        echo "- **ESLint check**: ✅ Passed" >> $GITHUB_STEP_SUMMARY
        echo "- **Build command**: npm run build" >> $GITHUB_STEP_SUMMARY
        echo "- **Status**: ✅ Success" >> $GITHUB_STEP_SUMMARY

    - name: Build failure summary
      if: failure()
      run: |
        echo "## ❌ Build Check Failed" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "The application failed to build or lint. Please check the logs above for errors." >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "Common issues:" >> $GITHUB_STEP_SUMMARY
        echo "- ESLint errors or warnings" >> $GITHUB_STEP_SUMMARY
        echo "- TypeScript/JavaScript syntax errors" >> $GITHUB_STEP_SUMMARY
        echo "- Missing dependencies" >> $GITHUB_STEP_SUMMARY
        echo "- Import/export issues" >> $GITHUB_STEP_SUMMARY
